version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"

python:
  install:
    - requirements: docs/doc_requirements.txt
    - method: pip
      path: .
