
approach: 1

# 1: parallel rxn-enum & div-enum in each rule
# 2: find recent solution, perform iteration (not too much in parallel!)
# 3: rxn-enum -> concat -> div-enum
# rxn: just perform rxn-enum
# icut: just perform icut
# max: just perform maxdist
# div: just perform div-enum

model: toy_models/small4M.json
# path to a cobrapy-compatible model (sbml, matlab or json format)

reaction-weights: toy_models/small4M_weights.csv
# path to a reaction-weight csv file

output_path: cluster/
# Folder to which the files are written. The folder will be created if not present

parallel_batches: 100
# number of parallel batches to run

enum_iterations: 100
# number of enumeration iterations per batch

rxn_iterations: 100
# number of reaction-enumeration iterations per batch (ONLY for approach 1 & 3)

cplex_path: /home/mstingl/save/CPLEX_Studio1210/cplex/python/3.7/x86-64_linux
# path to the installation of the CPLEX solver
# set to 'false' when not in use

starting_solution: false
# an imat solution to be used as a starting point for enumeration, optional input
# set to 'false' when not in use

reaction_list: false
# list of reactions in the model, optional input for reaction-enumeration
# set to 'false' when not in use


